kong:
  admin:
    enabled: false
  manager:
    enabled: false # Do not start the management UI
  env:
    database: "off"
    dns_order: A,CNAME,LAST,SRV
  dblessConfig:
    # PROBLEM: cannot use "{{ .Release.Name }}-kong-config" because templating does not work in values.yml
    configMap: kong-config
  ingressController:
    enabled: false
  proxy:
    type: NodePort
    http:
      nodePort: 31081
    tls:
      enabled: false
