kong:
  admin:
    enabled: false
  env:
    database: "off"
    dns_order: A,CNAME,LAST,SRV
    # dns_no_sync: "on"
  dblessConfig:
    configMap: kong-config
  ingressController:
    enabled: false
  proxy:
    type: NodePort
    http:
      nodePort: 31081
