apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  kong.yml: |
    _format_version: "3.0"
    _transform: true
    services:
    - name: nginx
      url: http://{{ .Release.Name }}-nginx
      routes:
      - name: nginx
        paths:
        - /
