apiVersion: v1
kind: ConfigMap
metadata:
  # PROBLEM: cannot use {{ .Release.Name }} here because referenced in values.yml
  name: {{ .Values.kong.dblessConfig.configMap }}
data:
  kong.yml: |
    _format_version: "3.0"
    _transform: true
    services:
    - name: nginx
      url: http://{{ .Release.Name }}-nginx
      routes:
      - name: nginx
        paths:
        - /
